### ISSUE TITLE
Issue while downloading thumbnails

### ISSUE THREAD

**Issue by DanielOaks** [bibanon/BASC-Archiver#18]
Got this while downloading threads and thumbnails and such, on the `threaded` branch.

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "<etc>/basc_archiver/sites/base.py", line 60, in run
    self.site.download_item(next_item)
  File "<etc>/basc_archiver/sites/fourchan.py", line 217, in download_item
    self.threads[thread_id]['total_files'] = len(list(running_thread.filenames()))
UnboundLocalError: local variable 'running_thread' referenced before assignment
```

**Comment by DanielOaks** [comment]
Fixed in f3f0eb8b7f617ef1875e6f4942e87f6cc2f5bf40
