### ISSUE TITLE
PyPi install failure

### ISSUE THREAD

**Issue by HASJ** [bibanon/BASC-Archiver#29]
```
Collecting basc-archiver
  Using cached BASC-Archiver-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Dudu\AppData\Local\Temp\pip-build-oqsbf0f3\basc-archiver\setup.py", line 17, in <module>
        long_description = file.read()
      File "c:\users\dudu\appdata\local\programs\python\python35\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1142: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Dudu\AppData\Local\Temp\pip-build-oqsbf0f3\basc-archiver
```

**Comment by DanielOaks** [comment]
Just curious, what version of Python are you using? (python --version`). We should work with Py2 and Py3, but my guess is it probably has something to do with Py2 being bad at unicode.

**Comment by HASJ** [comment]
v3.5.1

**Comment by DanielOaks** [comment]
Hmm, will look at this when I can get 3.5 running.

**Comment by HASJ** [comment]
Ok, I downgraded to 3.4.3 to check another thing and pip can't install it either.
I'm pretty sure it is something to do with me using a PT-BR installation of Windows as I've ran into some troubles with that and Python (not Python, per se, but the original code not handling a language other than english well).

PyPi traceback:
```
pip install basc-archiver
Collecting basc-archiver
  Using cached BASC-Archiver-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dudu\AppData\Local\Temp\pip-build-gfpjznd7\basc-archiver\setup.py", line 17, in <module>
        long_description = file.read()
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1142: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Dudu\AppData\Local\Temp\pip-build-gfpjznd7\basc-archiver
```
YouTube-DL installed just fine.

I downloaded the source and tried to install from it:
```
setup.py
Traceback (most recent call last):
  File "D:\Programas\4chanarchiver\BASC-Archiver-0.9.3\setup.py", line 18, in <module>
    long_description = file.read()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1142: character maps to <undefined>
```

So I modified line 18 to:
```
long_description ='4chanarchiver'
```

And voilà
```
setup.py install
running install
running bdist_egg
running egg_info
creating BASC_Archiver.egg-info
writing requirements to BASC_Archiver.egg-info\requires.txt
writing BASC_Archiver.egg-info\PKG-INFO
writing top-level names to BASC_Archiver.egg-info\top_level.txt
writing dependency_links to BASC_Archiver.egg-info\dependency_links.txt
writing manifest file 'BASC_Archiver.egg-info\SOURCES.txt'
reading manifest file 'BASC_Archiver.egg-info\SOURCES.txt'
writing manifest file 'BASC_Archiver.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\basc_archiver
copying basc_archiver\utils.py -> build\lib\basc_archiver
copying basc_archiver\__init__.py -> build\lib\basc_archiver
creating build\lib\basc_archiver\sites
copying basc_archiver\sites\base.py -> build\lib\basc_archiver\sites
copying basc_archiver\sites\fourchan.py -> build\lib\basc_archiver\sites
copying basc_archiver\sites\fuuka.py -> build\lib\basc_archiver\sites
copying basc_archiver\sites\__init__.py -> build\lib\basc_archiver\sites
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\basc_archiver
creating build\bdist.win-amd64\egg\basc_archiver\sites
copying build\lib\basc_archiver\sites\base.py -> build\bdist.win-amd64\egg\basc_archiver\sites
copying build\lib\basc_archiver\sites\fourchan.py -> build\bdist.win-amd64\egg\basc_archiver\sites
copying build\lib\basc_archiver\sites\fuuka.py -> build\bdist.win-amd64\egg\basc_archiver\sites
copying build\lib\basc_archiver\sites\__init__.py -> build\bdist.win-amd64\egg\basc_archiver\sites
copying build\lib\basc_archiver\utils.py -> build\bdist.win-amd64\egg\basc_archiver
copying build\lib\basc_archiver\__init__.py -> build\bdist.win-amd64\egg\basc_archiver
byte-compiling build\bdist.win-amd64\egg\basc_archiver\sites\base.py to base.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\basc_archiver\sites\fourchan.py to fourchan.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\basc_archiver\sites\fuuka.py to fuuka.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\basc_archiver\sites\__init__.py to __init__.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\basc_archiver\utils.py to utils.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\basc_archiver\__init__.py to __init__.cpython-34.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
creating build\scripts-3.4
copying and adjusting thread-archiver -> build\scripts-3.4
copying and adjusting 4chan-thread-archiver -> build\scripts-3.4
copying and adjusting archive-nabber -> build\scripts-3.4
creating build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.4\4chan-thread-archiver -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.4\archive-nabber -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.4\thread-archiver -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying BASC_Archiver.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying BASC_Archiver.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying BASC_Archiver.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying BASC_Archiver.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying BASC_Archiver.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\BASC_Archiver-0.9.3-py3.4.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing BASC_Archiver-0.9.3-py3.4.egg
Copying BASC_Archiver-0.9.3-py3.4.egg to c:\python34\lib\site-packages
Adding BASC-Archiver 0.9.3 to easy-install.pth file
Installing thread-archiver script to C:\Python34\Scripts
Installing archive-nabber script to C:\Python34\Scripts
Installing 4chan-thread-archiver script to C:\Python34\Scripts

Installed c:\python34\lib\site-packages\basc_archiver-0.9.3-py3.4.egg
Processing dependencies for BASC-Archiver==0.9.3
Searching for BASC-py4chan>=0.5.5
Reading https://pypi.python.org/simple/BASC-py4chan/
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.4.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.4.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.4.2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.4.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.5.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.5.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.5.2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.5.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.5.4)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.5.5)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
C:\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning: 'BASC (py4chan-0.6.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
Best match: BASC-py4chan 0.6.0
Downloading https://pypi.python.org/packages/source/B/BASC-py4chan/BASC-py4chan-0.6.0.tar.gz#md5=d4c22522afce735c854293e85e4e553e
Processing BASC-py4chan-0.6.0.tar.gz
Writing C:\Users\Dudu\AppData\Local\Temp\easy_install-d6hscw96\BASC-py4chan-0.6.0\setup.cfg
Running BASC-py4chan-0.6.0\setup.py -q bdist_egg --dist-dir C:\Users\Dudu\AppData\Local\Temp\easy_install-d6hscw96\BASC-py4chan-0.6.0\egg-dist-tmp-w6ktwpkt
zip_safe flag not set; analyzing archive contents...
Copying basc_py4chan-0.6.0-py3.4.egg to c:\python34\lib\site-packages
Adding basc-py4chan 0.6.0 to easy-install.pth file

Installed c:\python34\lib\site-packages\basc_py4chan-0.6.0-py3.4.egg
Searching for docopt==0.5.0
Reading https://pypi.python.org/simple/docopt/
Best match: docopt 0.5.0
Downloading https://pypi.python.org/packages/source/d/docopt/docopt-0.5.0.tar.gz#md5=989daa2e653346a98617309ef92c2947
Processing docopt-0.5.0.tar.gz
Writing C:\Users\Dudu\AppData\Local\Temp\easy_install-kh9euztz\docopt-0.5.0\setup.cfg
Running docopt-0.5.0\setup.py -q bdist_egg --dist-dir C:\Users\Dudu\AppData\Local\Temp\easy_install-kh9euztz\docopt-0.5.0\egg-dist-tmp-1ijoxx0u
zip_safe flag not set; analyzing archive contents...
Copying docopt-0.5.0-py3.4.egg to c:\python34\lib\site-packages
Adding docopt 0.5.0 to easy-install.pth file

Installed c:\python34\lib\site-packages\docopt-0.5.0-py3.4.egg
Searching for requests
Reading https://pypi.python.org/simple/requests/
Best match: requests 2.9.1
Downloading https://pypi.python.org/packages/source/r/requests/requests-2.9.1.tar.gz#md5=0b7f480d19012ec52bab78292efd976d
Processing requests-2.9.1.tar.gz
Writing C:\Users\Dudu\AppData\Local\Temp\easy_install-qhu0vhek\requests-2.9.1\setup.cfg
Running requests-2.9.1\setup.py -q bdist_egg --dist-dir C:\Users\Dudu\AppData\Local\Temp\easy_install-qhu0vhek\requests-2.9.1\egg-dist-tmp-ybu3n8dl
creating c:\python34\lib\site-packages\requests-2.9.1-py3.4.egg
Extracting requests-2.9.1-py3.4.egg to c:\python34\lib\site-packages
Adding requests 2.9.1 to easy-install.pth file

Installed c:\python34\lib\site-packages\requests-2.9.1-py3.4.egg
Finished processing dependencies for BASC-Archiver==0.9.3
```
Now I have three extentionless files in the scripts folder inside my Python installation and I have no idea how to use them. I'm very aware this could be a very dumb question but, help? @DanielOaks

**Comment by HASJ** [comment]
Poking around, I think I managed to compile the damn thing, lol. After running `setup.py build` a build_cli.py file popped up so I tried to `build_cli.py build` it.

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "thread-archiver", line 10, in <module>
    from basc_archiver import version, Options, Archiver
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
  File "D:\Programas\4chanarchiver\BASC-Archiver-0.9.3\basc_archiver\__init__.py", line 8, in <module>
    from .sites import default_archivers
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
  File "D:\Programas\4chanarchiver\BASC-Archiver-0.9.3\basc_archiver\sites\__init__.py", line 7, in <module>
    from . import fourchan
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2284, in _handle_fromlist
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 321, in _call_with_frames_removed
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
  File "D:\Programas\4chanarchiver\BASC-Archiver-0.9.3\basc_archiver\sites\fourchan.py", line 10, in <module>
    import basc_py4chan
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2224, in _find_and_load_unlocked
ImportError: No module named 'basc_py4chan'
```
But I don't really understand what I'm doing, just connecting dots. I'm not a engineer. Help? (lol)
