### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by Zerglingexe** [bibanon/BASC-Archiver#40]
Please forgive the noob question, but how does one go about installing the upgrades like 0.9.6? I've tried numerous things to do it, but have been unable to make any progress on it. I am on Windows.

**Comment by antonizoon** [comment]
Suffice to say, Windows is not our primarily supported operating system, and I myself don't know how to build for it. But I'll inform Dan about making a new build for windows.

However, if you have Windows 10, you can just install Ubuntu Linux as a command line subsystem! Then you just follow the Linux instructions.

https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by Hrxn** [comment]
Did you try it with `pip3 install basc-archiver` on Windows?

**Comment by Zerglingexe** [comment]
I did try that and got this log from pip:
------------------------------------------------------------
C:\Python34\Scripts\pip-script.py run on 01/06/17 14:43:28
Downloading/unpacking basic-archiver
  Getting page https://pypi.python.org/simple/basic-archiver/
  Could not fetch URL https://pypi.python.org/simple/basic-archiver/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/basic-archiver/ when looking for download links for basic-archiver
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for basic-archiver:
  * https://pypi.python.org/simple/basic-archiver/
  Getting page https://pypi.python.org/simple/basic-archiver/
  Could not fetch URL https://pypi.python.org/simple/basic-archiver/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/basic-archiver/ when looking for download links for basic-archiver
  Could not find any downloads that satisfy the requirement basic-archiver
Cleaning up...
  Removing temporary dir C:\Users\Zachary\AppData\Local\Temp\pip_build_Zachary...
No distributions at all found for basic-archiver
Exception information:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "C:\Python34\lib\site-packages\pip\index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for basic-archiver

**Comment by antonizoon** [comment]
Surprising that you managed to install pip on windows. You just misspelled the package name, please copy and paste:

```
pip3 install basc-archiver
```

**Comment by Zerglingexe** [comment]
That gives me this error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1142: character maps to <undefined>

**Comment by najloa** [comment]
Try this:
`sudo apt install python3-pip`
`pip3 install --upgrade pip`

**Comment by diVineProportion** [comment]
I didn't have to use WSL before. In the more verbose crash info above the UnicodeDecodeError it seems that something is problematic with the 1252 codepage. So I grabbed the master and tried to easy install and I got the same error about unicode.  [This](https://stackoverflow.com/questions/49640513/unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d-in-position-x-charac?rq=1) mentions the readme being problematic and that double quotes or the stdout >> character was the issue. 

Opened the readme and saved encoding in 1252 and no more error, just don't know how to install it. 

I did python setup.py install on both 'setup.py' and the '4chan-thread-archiver-setup.py' and it appeared to install correctly, not sure yet cause I think I'm dealing with external issues.

If you wanna try messing with the readme, I can test out the PyPI for you on windows.
